name: screen_util_example
description: An example on how to use flutter_screenutil with Widgetbook. 

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  widgetbook_annotation:
    git:
      url: https://github.com/devfelipereis/widgetbook
      path: packages/widgetbook_annotation
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  widgetbook: ^3.0.0-beta.14
  widgetbook_generator: ^3.0.0-beta.11
  build_runner: ^2.3.3

flutter:
  uses-material-design: true