name: widgetbook_annotation
description: A package featuring the annotations used by widgetbook_generator.
version: 2.1.0
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_annotation
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io/widgetbook-annotation/overview
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  widgetbook_models:
    git:
      url: https://github.com/devfelipereis/widgetbook
      path: packages/widgetbook_models
      ref: upgrade-flutter-3.10

dev_dependencies:
  test: ^1.18.2
  very_good_analysis: ^3.0.0
